[package]
name = "startup-base"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.0"
figment = { version = "0.10.6", features = ["env", "yaml"] }
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-zipkin = { version = "0.15.0", features = ["reqwest-client"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
tracing = "0.1.30"
tracing-opentelemetry = "0.17.0"
tracing-subscriber = { version = "0.3.8", features = ["fmt", "registry"] }
